on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksapp123.azurecr.io
        username: ${{ secrets.acr_aksapp123_username }}
        password: ${{ secrets.acr_aksapp123_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/E-Mall" -f  "E-Mall/Dockerfile" -t aksapp123.azurecr.io/aks:${{ github.sha }}
        docker push aksapp123.azurecr.io/aks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksa20b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksa20b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksa20b
        container-registry-url: aksapp123.azurecr.io
        container-registry-username: ${{ secrets.acr_aksapp123_username }}
        container-registry-password: ${{ secrets.acr_aksapp123_password }}
        secret-name: aksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksa20b
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          aksapp123.azurecr.io/aks:${{ github.sha }}
        imagepullsecrets: |
          aksdockerauth